### ISSUE TITLE
This Add-on is Great

### ISSUE THREAD

**Issue by Ramanuta** [gignupg/Movie-Subtitles#4]
Hello, this is no Issue Report, i just wanted to say, that i love this project. This Add-on is great, and it works great. It does what it is supposed to do, and it's super easy to use. I really have to thank the Creator for this. You did create something amazing here, and i thank you for that.

**Comment by gignupg** [comment]
Hey @Ramanuta, Thanks so much for your feedback!! I'm really glad people actually find it useful!

**Comment by Stathman** [comment]
Hi there. I would also like to say thank you for this great extension!
Allow me to ask a question. Is there a way to not show the "Silence (xx seconds)" message?
Thanks again, cheers!

![example](https://user-images.githubusercontent.com/16063390/151680731-0645accf-be28-45f3-b995-b27eee273871.png)

**Comment by gignupg** [comment]
Thank you @Stathman! 
Yes, it is possible to turn off the silence indicator! I totally forgot to mention this in the documentation. I updated it now! Simply click on the extension icon to open the subtitle settings, then below the Synchronization section, you can toggle the Silence Indicator on and off ;)

P.S. The new version of Movie Subtitles will have the silence indicator disabled by default since most people don't need it!
